pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            environment {
                GOCACHE = '/tmp/go-build-cache'
            }

            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
